### PR TITLE
Message feature update

### PR DESCRIPTION
**Pull request by alanensastegui**
Messages are now private. When logged in a user visiting their own page will see links to all their convos. Bug (or better said additional feature?) a link to a convo shows on an user's OWN profile page only if the recipient of the convo has replied. 

When viewing others page, a link to the convo between the logged in user and the profile they are visiting will show even if no convo exists

Changed messages to be sorted and displayed in sorted order (more natural and like existing messaging platforms). Also moved message form to the bottom of the convo page

### CODE REVIEW

**Comment by camsim99** [comment]
How exactly do you send to a person? Or is it still that weird thing where you have to specify the recipient in the url?

**Comment by alanensastegui** [comment]
> How exactly do you send to a person? Or is it still that weird thing where you have to specify the recipient in the url?

Its the same as before. However, instead of the message being posted on their feed, the message is sent and a conversation is created between you and the person you sent the message to

EDIT: nvm I think I misunderstood your question
That is how you could visit someones page. However, the more formal way would be by contacting the person through the ad they posted. That way it would be easy to message someone who made a posting, but hard to message someone who does not have an active posting. Since our application is meant to help people find roommates, I implemented it this way so the natural flow would be users messaging each other through public ad postings

**Comment by camsim99** [comment]
Ohhh I see! So basically they visit another user's page and they send them a message there. Gotcha!

**Comment by camsim99** [comment]
hey @1alan98  I really like this :) Can i just suggest you change "Convo" to something like "Direct Message" or if you wanna be really fancy "Direct Message With <the user>".  That might be a little hard but yeah I would just change to "Direct Message" or "Conversation"

**Review by Tetheta — APPROVED** [review]
If we were maintaining, we'd separate createLink to its own utils.js file and do a few other things, but this is fine for this kind of fast paced dev :) 

Neat to see this updated! Ping Camille for final approval but looks fine to me.

**Pull request merged**
