### PR TITLE
Feature messages

### PR DESCRIPTION
**Pull request by alanensastegui**
Added functionality for all users who are logged in to post messages on the pages of any other existing user. This required a changed logic in the logic of showMessagesIfViewingSelf (now called showMessagesIfLoggedIn), unsure if this might break the About Me section

### CODE REVIEW

**Comment by Tetheta** [comment]
Make sure to merge in master to resolve conflicts

**Review by Tetheta — COMMENTED** [review]
So sounds like you're considering a "self message" to be the old regular post?

Seems reasonable.

Merge master into this and make sure your change of getMessages doesn't mess up anyone else's stuff. Whenever you refactor something there's always that risk.

**Comment by tiyingxu** [comment]
I'm getting a loading screen when I try to log in and go into the user's page. Maybe the showMessagesIfLoggedIn part is also breaking the whole "look at my page" part? Not sure if it's just my computer though

**Comment by tiyingxu** [comment]
Alright so the messages seem to be working fine now, not sure how to test the direct messages though. This may be because there is only one user on your local server right now; can you add one dummy user to see if you can send them messages?

Also, this does affect the about me section but that's probably because you haven't pulled from master when you created this branch and my stuff isn't on here yet

**Review by Tetheta — DISMISSED** [review]

**Review by Tetheta — APPROVED** [review]
LGTM

**Comment by Tetheta** [comment]
Looks good to me, ignore the prettier linting checks, we'll fix that in the team meeting this week

**Pull request merged**
