### PR TITLE
Feature matches feed

### PR DESCRIPTION
**Pull request by alanensastegui**
Added a simple matches feed page. Gets the all postings except those made by the logged in user. The postings are shown in a page and are sorted by distance to the user. Postings include a title, link to profile of poster, description and price

### CODE REVIEW

**Comment by faesalm** [comment]
can you fix stickler being funky and conflicts so i can test/merge?

**Comment by faesalm** [comment]
Looks good to me. I will be adding ability to post items soon. Can you make this page display every item + user info associated with item?

**Comment by faesalm** [comment]
Is this a superset of the other branch (matches feed style) ?

**Comment by alanensastegui** [comment]
> Is this a superset of the other branch (matches feed style) ?

Yes, I just closed the other PR

**Comment by faesalm** [comment]
Looks great to me. Images can be their own PR in a few days as they are not complete yet (for posting or profile). 
How are you calculating distance here? Is there any actual value (km, miles) associated to it or is it just coordinate math? Would be great if you can see distance of each posting from you (will also help validate this is actually working). It does not have to be part of this PR. I am just making sure we are not losing that info down the road

**Pull request merged**
